// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/Layout.vue')['default']
    ListBlogs: typeof import('./src/components/List/Blogs.vue')['default']
    ListProjects: typeof import('./src/components/List/Projects.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stars: typeof import('./src/components/Stars.vue')['default']
    UnsplashImage: typeof import('./src/components/UnsplashImage.vue')['default']
  }
}

export {}
